language: go

go:
  - "1.10"

services:
  - docker

before_script:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - curl -fSL https://releases.hashicorp.com/nomad/0.8.6/nomad_0.8.6_linux_amd64.zip -o nomad.zip
  - sudo unzip nomad.zip -d /opt/nomad
  - sudo ln -s /opt/nomad/nomad /usr/bin/nomad
  - rm -f nomad_0.8.6_linux_amd64.zip
  - nohup nomad agent --dev &

script:
  - make protodep
  - export PROTO_VERSION=3.5.1
  - export PATH="/tmp/proto/${PROTO_VERSION}/bin/":$PATH
  - docker-compose -f docker-compose.yaml up -d consul
  - sleep 5
  - make all_test
  - export TSL8_WORKER_CONSUL_IP="127.0.0.1:8500"
  - make all_test
  - make build_images

deploy:
  - provider: script
    script: make upload_images
    on:
      branch: master
