language: go

go:
  - "1.10"

services:
  - docker

before_script:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

script:
  - make protodep
  - export PROTO_VERSION=3.5.1
  - export PATH="/tmp/proto/${PROTO_VERSION}/bin/":$PATH
  - docker-compose -f docker-compose.yaml up -d consul
  - sleep 5
  - make cli_build
  - make test
  - make build_images

deploy:
  - provider: script
    script: make upload_images
    on:
      branch: master
