// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tessellate.proto

package server // import "github.com/tsocial/tessellate/server"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/lyft/protoc-gen-validate/validate"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Errors int32

const (
	Errors_NOT_ALLOWED    Errors = 0
	Errors_NOT_FOUND      Errors = 1
	Errors_LOCKED         Errors = 2
	Errors_INTERNAL_ERROR Errors = 3
	Errors_INVALID_VALUE  Errors = 4
	Errors_MISSING_VALUE  Errors = 5
)

var Errors_name = map[int32]string{
	0: "NOT_ALLOWED",
	1: "NOT_FOUND",
	2: "LOCKED",
	3: "INTERNAL_ERROR",
	4: "INVALID_VALUE",
	5: "MISSING_VALUE",
}
var Errors_value = map[string]int32{
	"NOT_ALLOWED":    0,
	"NOT_FOUND":      1,
	"LOCKED":         2,
	"INTERNAL_ERROR": 3,
	"INVALID_VALUE":  4,
	"MISSING_VALUE":  5,
}

func (x Errors) String() string {
	return proto.EnumName(Errors_name, int32(x))
}
func (Errors) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_tessellate_561282f3b06ec83b, []int{0}
}

type Status int32

const (
	Status_INACTIVE Status = 0
	Status_ACTIVE   Status = 1
)

var Status_name = map[int32]string{
	0: "INACTIVE",
	1: "ACTIVE",
}
var Status_value = map[string]int32{
	"INACTIVE": 0,
	"ACTIVE":   1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_tessellate_561282f3b06ec83b, []int{1}
}

type JobState int32

const (
	JobState_PENDING JobState = 0
	JobState_RUNNING JobState = 1
	JobState_FAILED  JobState = 2
	JobState_ABORTED JobState = 3
	JobState_DONE    JobState = 4
	JobState_ERROR   JobState = 5
)

var JobState_name = map[int32]string{
	0: "PENDING",
	1: "RUNNING",
	2: "FAILED",
	3: "ABORTED",
	4: "DONE",
	5: "ERROR",
}
var JobState_value = map[string]int32{
	"PENDING": 0,
	"RUNNING": 1,
	"FAILED":  2,
	"ABORTED": 3,
	"DONE":    4,
	"ERROR":   5,
}

func (x JobState) String() string {
	return proto.EnumName(JobState_name, int32(x))
}
func (JobState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_tessellate_561282f3b06ec83b, []int{2}
}

type Operation int32

const (
	Operation_APPLY   Operation = 0
	Operation_DESTROY Operation = 1
)

var Operation_name = map[int32]string{
	0: "APPLY",
	1: "DESTROY",
}
var Operation_value = map[string]int32{
	"APPLY":   0,
	"DESTROY": 1,
}

func (x Operation) String() string {
	return proto.EnumName(Operation_name, int32(x))
}
func (Operation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_tessellate_561282f3b06ec83b, []int{3}
}

type GetWorkspaceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWorkspaceRequest) Reset()         { *m = GetWorkspaceRequest{} }
func (m *GetWorkspaceRequest) String() string { return proto.CompactTextString(m) }
func (*GetWorkspaceRequest) ProtoMessage()    {}
func (*GetWorkspaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tessellate_561282f3b06ec83b, []int{0}
}
func (m *GetWorkspaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkspaceRequest.Unmarshal(m, b)
}
func (m *GetWorkspaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkspaceRequest.Marshal(b, m, deterministic)
}
func (dst *GetWorkspaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkspaceRequest.Merge(dst, src)
}
func (m *GetWorkspaceRequest) XXX_Size() int {
	return xxx_messageInfo_GetWorkspaceRequest.Size(m)
}
func (m *GetWorkspaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkspaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkspaceRequest proto.InternalMessageInfo

func (m *GetWorkspaceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Workspace struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Vars                 []byte   `protobuf:"bytes,2,opt,name=Vars,proto3" json:"Vars,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`
	Versions             []string `protobuf:"bytes,4,rep,name=Versions,proto3" json:"Versions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Workspace) Reset()         { *m = Workspace{} }
func (m *Workspace) String() string { return proto.CompactTextString(m) }
func (*Workspace) ProtoMessage()    {}
func (*Workspace) Descriptor() ([]byte, []int) {
	return fileDescriptor_tessellate_561282f3b06ec83b, []int{1}
}
func (m *Workspace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Workspace.Unmarshal(m, b)
}
func (m *Workspace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Workspace.Marshal(b, m, deterministic)
}
func (dst *Workspace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Workspace.Merge(dst, src)
}
func (m *Workspace) XXX_Size() int {
	return xxx_messageInfo_Workspace.Size(m)
}
func (m *Workspace) XXX_DiscardUnknown() {
	xxx_messageInfo_Workspace.DiscardUnknown(m)
}

var xxx_messageInfo_Workspace proto.InternalMessageInfo

func (m *Workspace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Workspace) GetVars() []byte {
	if m != nil {
		return m.Vars
	}
	return nil
}

func (m *Workspace) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Workspace) GetVersions() []string {
	if m != nil {
		return m.Versions
	}
	return nil
}

type Layouts struct {
	Layouts              []*Layout `protobuf:"bytes,1,rep,name=layouts,proto3" json:"layouts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Layouts) Reset()         { *m = Layouts{} }
func (m *Layouts) String() string { return proto.CompactTextString(m) }
func (*Layouts) ProtoMessage()    {}
func (*Layouts) Descriptor() ([]byte, []int) {
	return fileDescriptor_tessellate_561282f3b06ec83b, []int{2}
}
func (m *Layouts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Layouts.Unmarshal(m, b)
}
func (m *Layouts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Layouts.Marshal(b, m, deterministic)
}
func (dst *Layouts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Layouts.Merge(dst, src)
}
func (m *Layouts) XXX_Size() int {
	return xxx_messageInfo_Layouts.Size(m)
}
func (m *Layouts) XXX_DiscardUnknown() {
	xxx_messageInfo_Layouts.DiscardUnknown(m)
}

var xxx_messageInfo_Layouts proto.InternalMessageInfo

func (m *Layouts) GetLayouts() []*Layout {
	if m != nil {
		return m.Layouts
	}
	return nil
}

type Layout struct {
	Workspaceid          string   `protobuf:"bytes,1,opt,name=Workspaceid,proto3" json:"Workspaceid,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Plan                 []byte   `protobuf:"bytes,3,opt,name=Plan,proto3" json:"Plan,omitempty"`
	Vars                 []byte   `protobuf:"bytes,4,opt,name=Vars,proto3" json:"Vars,omitempty"`
	Status               Status   `protobuf:"varint,5,opt,name=Status,proto3,enum=tsocial.tessellate.server.Status" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Layout) Reset()         { *m = Layout{} }
func (m *Layout) String() string { return proto.CompactTextString(m) }
func (*Layout) ProtoMessage()    {}
func (*Layout) Descriptor() ([]byte, []int) {
	return fileDescriptor_tessellate_561282f3b06ec83b, []int{3}
}
func (m *Layout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Layout.Unmarshal(m, b)
}
func (m *Layout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Layout.Marshal(b, m, deterministic)
}
func (dst *Layout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Layout.Merge(dst, src)
}
func (m *Layout) XXX_Size() int {
	return xxx_messageInfo_Layout.Size(m)
}
func (m *Layout) XXX_DiscardUnknown() {
	xxx_messageInfo_Layout.DiscardUnknown(m)
}

var xxx_messageInfo_Layout proto.InternalMessageInfo

func (m *Layout) GetWorkspaceid() string {
	if m != nil {
		return m.Workspaceid
	}
	return ""
}

func (m *Layout) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Layout) GetPlan() []byte {
	if m != nil {
		return m.Plan
	}
	return nil
}

func (m *Layout) GetVars() []byte {
	if m != nil {
		return m.Vars
	}
	return nil
}

func (m *Layout) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_INACTIVE
}

type SaveWorkspaceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Vars                 []byte   `protobuf:"bytes,2,opt,name=Vars,proto3" json:"Vars,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveWorkspaceRequest) Reset()         { *m = SaveWorkspaceRequest{} }
func (m *SaveWorkspaceRequest) String() string { return proto.CompactTextString(m) }
func (*SaveWorkspaceRequest) ProtoMessage()    {}
func (*SaveWorkspaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tessellate_561282f3b06ec83b, []int{4}
}
func (m *SaveWorkspaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveWorkspaceRequest.Unmarshal(m, b)
}
func (m *SaveWorkspaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveWorkspaceRequest.Marshal(b, m, deterministic)
}
func (dst *SaveWorkspaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveWorkspaceRequest.Merge(dst, src)
}
func (m *SaveWorkspaceRequest) XXX_Size() int {
	return xxx_messageInfo_SaveWorkspaceRequest.Size(m)
}
func (m *SaveWorkspaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveWorkspaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveWorkspaceRequest proto.InternalMessageInfo

func (m *SaveWorkspaceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SaveWorkspaceRequest) GetVars() []byte {
	if m != nil {
		return m.Vars
	}
	return nil
}

type GetWorkspaceLayoutsRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWorkspaceLayoutsRequest) Reset()         { *m = GetWorkspaceLayoutsRequest{} }
func (m *GetWorkspaceLayoutsRequest) String() string { return proto.CompactTextString(m) }
func (*GetWorkspaceLayoutsRequest) ProtoMessage()    {}
func (*GetWorkspaceLayoutsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tessellate_561282f3b06ec83b, []int{5}
}
func (m *GetWorkspaceLayoutsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkspaceLayoutsRequest.Unmarshal(m, b)
}
func (m *GetWorkspaceLayoutsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkspaceLayoutsRequest.Marshal(b, m, deterministic)
}
func (dst *GetWorkspaceLayoutsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkspaceLayoutsRequest.Merge(dst, src)
}
func (m *GetWorkspaceLayoutsRequest) XXX_Size() int {
	return xxx_messageInfo_GetWorkspaceLayoutsRequest.Size(m)
}
func (m *GetWorkspaceLayoutsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkspaceLayoutsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkspaceLayoutsRequest proto.InternalMessageInfo

func (m *GetWorkspaceLayoutsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type JobStatus struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Status               JobState `protobuf:"varint,2,opt,name=status,proto3,enum=tsocial.tessellate.server.JobState" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobStatus) Reset()         { *m = JobStatus{} }
func (m *JobStatus) String() string { return proto.CompactTextString(m) }
func (*JobStatus) ProtoMessage()    {}
func (*JobStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_tessellate_561282f3b06ec83b, []int{6}
}
func (m *JobStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobStatus.Unmarshal(m, b)
}
func (m *JobStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobStatus.Marshal(b, m, deterministic)
}
func (dst *JobStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobStatus.Merge(dst, src)
}
func (m *JobStatus) XXX_Size() int {
	return xxx_messageInfo_JobStatus.Size(m)
}
func (m *JobStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_JobStatus.DiscardUnknown(m)
}

var xxx_messageInfo_JobStatus proto.InternalMessageInfo

func (m *JobStatus) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JobStatus) GetStatus() JobState {
	if m != nil {
		return m.Status
	}
	return JobState_PENDING
}

type Vars struct {
	Vars                 []byte   `protobuf:"bytes,1,opt,name=Vars,proto3" json:"Vars,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vars) Reset()         { *m = Vars{} }
func (m *Vars) String() string { return proto.CompactTextString(m) }
func (*Vars) ProtoMessage()    {}
func (*Vars) Descriptor() ([]byte, []int) {
	return fileDescriptor_tessellate_561282f3b06ec83b, []int{7}
}
func (m *Vars) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vars.Unmarshal(m, b)
}
func (m *Vars) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vars.Marshal(b, m, deterministic)
}
func (dst *Vars) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vars.Merge(dst, src)
}
func (m *Vars) XXX_Size() int {
	return xxx_messageInfo_Vars.Size(m)
}
func (m *Vars) XXX_DiscardUnknown() {
	xxx_messageInfo_Vars.DiscardUnknown(m)
}

var xxx_messageInfo_Vars proto.InternalMessageInfo

func (m *Vars) GetVars() []byte {
	if m != nil {
		return m.Vars
	}
	return nil
}

type JobRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobRequest) Reset()         { *m = JobRequest{} }
func (m *JobRequest) String() string { return proto.CompactTextString(m) }
func (*JobRequest) ProtoMessage()    {}
func (*JobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tessellate_561282f3b06ec83b, []int{8}
}
func (m *JobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobRequest.Unmarshal(m, b)
}
func (m *JobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobRequest.Marshal(b, m, deterministic)
}
func (dst *JobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobRequest.Merge(dst, src)
}
func (m *JobRequest) XXX_Size() int {
	return xxx_messageInfo_JobRequest.Size(m)
}
func (m *JobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobRequest proto.InternalMessageInfo

func (m *JobRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Ok struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ok) Reset()         { *m = Ok{} }
func (m *Ok) String() string { return proto.CompactTextString(m) }
func (*Ok) ProtoMessage()    {}
func (*Ok) Descriptor() ([]byte, []int) {
	return fileDescriptor_tessellate_561282f3b06ec83b, []int{9}
}
func (m *Ok) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ok.Unmarshal(m, b)
}
func (m *Ok) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ok.Marshal(b, m, deterministic)
}
func (dst *Ok) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ok.Merge(dst, src)
}
func (m *Ok) XXX_Size() int {
	return xxx_messageInfo_Ok.Size(m)
}
func (m *Ok) XXX_DiscardUnknown() {
	xxx_messageInfo_Ok.DiscardUnknown(m)
}

var xxx_messageInfo_Ok proto.InternalMessageInfo

type LayoutRequest struct {
	WorkspaceId          string   `protobuf:"bytes,1,opt,name=WorkspaceId,proto3" json:"WorkspaceId,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LayoutRequest) Reset()         { *m = LayoutRequest{} }
func (m *LayoutRequest) String() string { return proto.CompactTextString(m) }
func (*LayoutRequest) ProtoMessage()    {}
func (*LayoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tessellate_561282f3b06ec83b, []int{10}
}
func (m *LayoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LayoutRequest.Unmarshal(m, b)
}
func (m *LayoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LayoutRequest.Marshal(b, m, deterministic)
}
func (dst *LayoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LayoutRequest.Merge(dst, src)
}
func (m *LayoutRequest) XXX_Size() int {
	return xxx_messageInfo_LayoutRequest.Size(m)
}
func (m *LayoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LayoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LayoutRequest proto.InternalMessageInfo

func (m *LayoutRequest) GetWorkspaceId() string {
	if m != nil {
		return m.WorkspaceId
	}
	return ""
}

func (m *LayoutRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SaveLayoutRequest struct {
	WorkspaceId          string   `protobuf:"bytes,1,opt,name=WorkspaceId,proto3" json:"WorkspaceId,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Plan                 []byte   `protobuf:"bytes,3,opt,name=Plan,proto3" json:"Plan,omitempty"`
	Vars                 []byte   `protobuf:"bytes,4,opt,name=Vars,proto3" json:"Vars,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveLayoutRequest) Reset()         { *m = SaveLayoutRequest{} }
func (m *SaveLayoutRequest) String() string { return proto.CompactTextString(m) }
func (*SaveLayoutRequest) ProtoMessage()    {}
func (*SaveLayoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tessellate_561282f3b06ec83b, []int{11}
}
func (m *SaveLayoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveLayoutRequest.Unmarshal(m, b)
}
func (m *SaveLayoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveLayoutRequest.Marshal(b, m, deterministic)
}
func (dst *SaveLayoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveLayoutRequest.Merge(dst, src)
}
func (m *SaveLayoutRequest) XXX_Size() int {
	return xxx_messageInfo_SaveLayoutRequest.Size(m)
}
func (m *SaveLayoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveLayoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveLayoutRequest proto.InternalMessageInfo

func (m *SaveLayoutRequest) GetWorkspaceId() string {
	if m != nil {
		return m.WorkspaceId
	}
	return ""
}

func (m *SaveLayoutRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SaveLayoutRequest) GetPlan() []byte {
	if m != nil {
		return m.Plan
	}
	return nil
}

func (m *SaveLayoutRequest) GetVars() []byte {
	if m != nil {
		return m.Vars
	}
	return nil
}

type SetLayoutStatusRequest struct {
	WorkspaceId          string   `protobuf:"bytes,1,opt,name=WorkspaceId,proto3" json:"WorkspaceId,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetLayoutStatusRequest) Reset()         { *m = SetLayoutStatusRequest{} }
func (m *SetLayoutStatusRequest) String() string { return proto.CompactTextString(m) }
func (*SetLayoutStatusRequest) ProtoMessage()    {}
func (*SetLayoutStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tessellate_561282f3b06ec83b, []int{12}
}
func (m *SetLayoutStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLayoutStatusRequest.Unmarshal(m, b)
}
func (m *SetLayoutStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLayoutStatusRequest.Marshal(b, m, deterministic)
}
func (dst *SetLayoutStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLayoutStatusRequest.Merge(dst, src)
}
func (m *SetLayoutStatusRequest) XXX_Size() int {
	return xxx_messageInfo_SetLayoutStatusRequest.Size(m)
}
func (m *SetLayoutStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLayoutStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetLayoutStatusRequest proto.InternalMessageInfo

func (m *SetLayoutStatusRequest) GetWorkspaceId() string {
	if m != nil {
		return m.WorkspaceId
	}
	return ""
}

func (m *SetLayoutStatusRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SetLayoutStatusRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ApplyLayoutRequest struct {
	WorkspaceId          string   `protobuf:"bytes,1,opt,name=WorkspaceId,proto3" json:"WorkspaceId,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Vars                 []byte   `protobuf:"bytes,3,opt,name=Vars,proto3" json:"Vars,omitempty"`
	Dry                  bool     `protobuf:"varint,4,opt,name=dry,proto3" json:"dry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyLayoutRequest) Reset()         { *m = ApplyLayoutRequest{} }
func (m *ApplyLayoutRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyLayoutRequest) ProtoMessage()    {}
func (*ApplyLayoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tessellate_561282f3b06ec83b, []int{13}
}
func (m *ApplyLayoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyLayoutRequest.Unmarshal(m, b)
}
func (m *ApplyLayoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyLayoutRequest.Marshal(b, m, deterministic)
}
func (dst *ApplyLayoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyLayoutRequest.Merge(dst, src)
}
func (m *ApplyLayoutRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyLayoutRequest.Size(m)
}
func (m *ApplyLayoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyLayoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyLayoutRequest proto.InternalMessageInfo

func (m *ApplyLayoutRequest) GetWorkspaceId() string {
	if m != nil {
		return m.WorkspaceId
	}
	return ""
}

func (m *ApplyLayoutRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ApplyLayoutRequest) GetVars() []byte {
	if m != nil {
		return m.Vars
	}
	return nil
}

func (m *ApplyLayoutRequest) GetDry() bool {
	if m != nil {
		return m.Dry
	}
	return false
}

type StartWatchRequest struct {
	WorkspaceId          string   `protobuf:"bytes,1,opt,name=WorkspaceId,proto3" json:"WorkspaceId,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	SuccessCallback      string   `protobuf:"bytes,3,opt,name=SuccessCallback,proto3" json:"SuccessCallback,omitempty"`
	FailureCallback      string   `protobuf:"bytes,4,opt,name=FailureCallback,proto3" json:"FailureCallback,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartWatchRequest) Reset()         { *m = StartWatchRequest{} }
func (m *StartWatchRequest) String() string { return proto.CompactTextString(m) }
func (*StartWatchRequest) ProtoMessage()    {}
func (*StartWatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tessellate_561282f3b06ec83b, []int{14}
}
func (m *StartWatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartWatchRequest.Unmarshal(m, b)
}
func (m *StartWatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartWatchRequest.Marshal(b, m, deterministic)
}
func (dst *StartWatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartWatchRequest.Merge(dst, src)
}
func (m *StartWatchRequest) XXX_Size() int {
	return xxx_messageInfo_StartWatchRequest.Size(m)
}
func (m *StartWatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartWatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartWatchRequest proto.InternalMessageInfo

func (m *StartWatchRequest) GetWorkspaceId() string {
	if m != nil {
		return m.WorkspaceId
	}
	return ""
}

func (m *StartWatchRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StartWatchRequest) GetSuccessCallback() string {
	if m != nil {
		return m.SuccessCallback
	}
	return ""
}

func (m *StartWatchRequest) GetFailureCallback() string {
	if m != nil {
		return m.FailureCallback
	}
	return ""
}

type StopWatchRequest struct {
	WorkspaceId          string   `protobuf:"bytes,1,opt,name=WorkspaceId,proto3" json:"WorkspaceId,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopWatchRequest) Reset()         { *m = StopWatchRequest{} }
func (m *StopWatchRequest) String() string { return proto.CompactTextString(m) }
func (*StopWatchRequest) ProtoMessage()    {}
func (*StopWatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tessellate_561282f3b06ec83b, []int{15}
}
func (m *StopWatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopWatchRequest.Unmarshal(m, b)
}
func (m *StopWatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopWatchRequest.Marshal(b, m, deterministic)
}
func (dst *StopWatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopWatchRequest.Merge(dst, src)
}
func (m *StopWatchRequest) XXX_Size() int {
	return xxx_messageInfo_StopWatchRequest.Size(m)
}
func (m *StopWatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopWatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopWatchRequest proto.InternalMessageInfo

func (m *StopWatchRequest) GetWorkspaceId() string {
	if m != nil {
		return m.WorkspaceId
	}
	return ""
}

func (m *StopWatchRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*GetWorkspaceRequest)(nil), "tsocial.tessellate.server.GetWorkspaceRequest")
	proto.RegisterType((*Workspace)(nil), "tsocial.tessellate.server.Workspace")
	proto.RegisterType((*Layouts)(nil), "tsocial.tessellate.server.Layouts")
	proto.RegisterType((*Layout)(nil), "tsocial.tessellate.server.Layout")
	proto.RegisterType((*SaveWorkspaceRequest)(nil), "tsocial.tessellate.server.SaveWorkspaceRequest")
	proto.RegisterType((*GetWorkspaceLayoutsRequest)(nil), "tsocial.tessellate.server.GetWorkspaceLayoutsRequest")
	proto.RegisterType((*JobStatus)(nil), "tsocial.tessellate.server.JobStatus")
	proto.RegisterType((*Vars)(nil), "tsocial.tessellate.server.Vars")
	proto.RegisterType((*JobRequest)(nil), "tsocial.tessellate.server.JobRequest")
	proto.RegisterType((*Ok)(nil), "tsocial.tessellate.server.Ok")
	proto.RegisterType((*LayoutRequest)(nil), "tsocial.tessellate.server.LayoutRequest")
	proto.RegisterType((*SaveLayoutRequest)(nil), "tsocial.tessellate.server.SaveLayoutRequest")
	proto.RegisterType((*SetLayoutStatusRequest)(nil), "tsocial.tessellate.server.SetLayoutStatusRequest")
	proto.RegisterType((*ApplyLayoutRequest)(nil), "tsocial.tessellate.server.ApplyLayoutRequest")
	proto.RegisterType((*StartWatchRequest)(nil), "tsocial.tessellate.server.StartWatchRequest")
	proto.RegisterType((*StopWatchRequest)(nil), "tsocial.tessellate.server.StopWatchRequest")
	proto.RegisterEnum("tsocial.tessellate.server.Errors", Errors_name, Errors_value)
	proto.RegisterEnum("tsocial.tessellate.server.Status", Status_name, Status_value)
	proto.RegisterEnum("tsocial.tessellate.server.JobState", JobState_name, JobState_value)
	proto.RegisterEnum("tsocial.tessellate.server.Operation", Operation_name, Operation_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TessellateClient is the client API for Tessellate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TessellateClient interface {
	SaveWorkspace(ctx context.Context, in *SaveWorkspaceRequest, opts ...grpc.CallOption) (*Ok, error)
	GetWorkspace(ctx context.Context, in *GetWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error)
	SaveLayout(ctx context.Context, in *SaveLayoutRequest, opts ...grpc.CallOption) (*Ok, error)
	GetLayout(ctx context.Context, in *LayoutRequest, opts ...grpc.CallOption) (*Layout, error)
	ApplyLayout(ctx context.Context, in *ApplyLayoutRequest, opts ...grpc.CallOption) (*JobStatus, error)
	DestroyLayout(ctx context.Context, in *ApplyLayoutRequest, opts ...grpc.CallOption) (*JobStatus, error)
	AbortJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*Ok, error)
	StartWatch(ctx context.Context, in *StartWatchRequest, opts ...grpc.CallOption) (*Ok, error)
	StopWatch(ctx context.Context, in *StopWatchRequest, opts ...grpc.CallOption) (*Ok, error)
}

type tessellateClient struct {
	cc *grpc.ClientConn
}

func NewTessellateClient(cc *grpc.ClientConn) TessellateClient {
	return &tessellateClient{cc}
}

func (c *tessellateClient) SaveWorkspace(ctx context.Context, in *SaveWorkspaceRequest, opts ...grpc.CallOption) (*Ok, error) {
	out := new(Ok)
	err := c.cc.Invoke(ctx, "/tsocial.tessellate.server.Tessellate/SaveWorkspace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tessellateClient) GetWorkspace(ctx context.Context, in *GetWorkspaceRequest, opts ...grpc.CallOption) (*Workspace, error) {
	out := new(Workspace)
	err := c.cc.Invoke(ctx, "/tsocial.tessellate.server.Tessellate/GetWorkspace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tessellateClient) SaveLayout(ctx context.Context, in *SaveLayoutRequest, opts ...grpc.CallOption) (*Ok, error) {
	out := new(Ok)
	err := c.cc.Invoke(ctx, "/tsocial.tessellate.server.Tessellate/SaveLayout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tessellateClient) GetLayout(ctx context.Context, in *LayoutRequest, opts ...grpc.CallOption) (*Layout, error) {
	out := new(Layout)
	err := c.cc.Invoke(ctx, "/tsocial.tessellate.server.Tessellate/GetLayout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tessellateClient) ApplyLayout(ctx context.Context, in *ApplyLayoutRequest, opts ...grpc.CallOption) (*JobStatus, error) {
	out := new(JobStatus)
	err := c.cc.Invoke(ctx, "/tsocial.tessellate.server.Tessellate/ApplyLayout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tessellateClient) DestroyLayout(ctx context.Context, in *ApplyLayoutRequest, opts ...grpc.CallOption) (*JobStatus, error) {
	out := new(JobStatus)
	err := c.cc.Invoke(ctx, "/tsocial.tessellate.server.Tessellate/DestroyLayout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tessellateClient) AbortJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*Ok, error) {
	out := new(Ok)
	err := c.cc.Invoke(ctx, "/tsocial.tessellate.server.Tessellate/AbortJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tessellateClient) StartWatch(ctx context.Context, in *StartWatchRequest, opts ...grpc.CallOption) (*Ok, error) {
	out := new(Ok)
	err := c.cc.Invoke(ctx, "/tsocial.tessellate.server.Tessellate/StartWatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tessellateClient) StopWatch(ctx context.Context, in *StopWatchRequest, opts ...grpc.CallOption) (*Ok, error) {
	out := new(Ok)
	err := c.cc.Invoke(ctx, "/tsocial.tessellate.server.Tessellate/StopWatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TessellateServer is the server API for Tessellate service.
type TessellateServer interface {
	SaveWorkspace(context.Context, *SaveWorkspaceRequest) (*Ok, error)
	GetWorkspace(context.Context, *GetWorkspaceRequest) (*Workspace, error)
	SaveLayout(context.Context, *SaveLayoutRequest) (*Ok, error)
	GetLayout(context.Context, *LayoutRequest) (*Layout, error)
	ApplyLayout(context.Context, *ApplyLayoutRequest) (*JobStatus, error)
	DestroyLayout(context.Context, *ApplyLayoutRequest) (*JobStatus, error)
	AbortJob(context.Context, *JobRequest) (*Ok, error)
	StartWatch(context.Context, *StartWatchRequest) (*Ok, error)
	StopWatch(context.Context, *StopWatchRequest) (*Ok, error)
}

func RegisterTessellateServer(s *grpc.Server, srv TessellateServer) {
	s.RegisterService(&_Tessellate_serviceDesc, srv)
}

func _Tessellate_SaveWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TessellateServer).SaveWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsocial.tessellate.server.Tessellate/SaveWorkspace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TessellateServer).SaveWorkspace(ctx, req.(*SaveWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tessellate_GetWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TessellateServer).GetWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsocial.tessellate.server.Tessellate/GetWorkspace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TessellateServer).GetWorkspace(ctx, req.(*GetWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tessellate_SaveLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TessellateServer).SaveLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsocial.tessellate.server.Tessellate/SaveLayout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TessellateServer).SaveLayout(ctx, req.(*SaveLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tessellate_GetLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TessellateServer).GetLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsocial.tessellate.server.Tessellate/GetLayout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TessellateServer).GetLayout(ctx, req.(*LayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tessellate_ApplyLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TessellateServer).ApplyLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsocial.tessellate.server.Tessellate/ApplyLayout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TessellateServer).ApplyLayout(ctx, req.(*ApplyLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tessellate_DestroyLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TessellateServer).DestroyLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsocial.tessellate.server.Tessellate/DestroyLayout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TessellateServer).DestroyLayout(ctx, req.(*ApplyLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tessellate_AbortJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TessellateServer).AbortJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsocial.tessellate.server.Tessellate/AbortJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TessellateServer).AbortJob(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tessellate_StartWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TessellateServer).StartWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsocial.tessellate.server.Tessellate/StartWatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TessellateServer).StartWatch(ctx, req.(*StartWatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tessellate_StopWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopWatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TessellateServer).StopWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tsocial.tessellate.server.Tessellate/StopWatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TessellateServer).StopWatch(ctx, req.(*StopWatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tessellate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tsocial.tessellate.server.Tessellate",
	HandlerType: (*TessellateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveWorkspace",
			Handler:    _Tessellate_SaveWorkspace_Handler,
		},
		{
			MethodName: "GetWorkspace",
			Handler:    _Tessellate_GetWorkspace_Handler,
		},
		{
			MethodName: "SaveLayout",
			Handler:    _Tessellate_SaveLayout_Handler,
		},
		{
			MethodName: "GetLayout",
			Handler:    _Tessellate_GetLayout_Handler,
		},
		{
			MethodName: "ApplyLayout",
			Handler:    _Tessellate_ApplyLayout_Handler,
		},
		{
			MethodName: "DestroyLayout",
			Handler:    _Tessellate_DestroyLayout_Handler,
		},
		{
			MethodName: "AbortJob",
			Handler:    _Tessellate_AbortJob_Handler,
		},
		{
			MethodName: "StartWatch",
			Handler:    _Tessellate_StartWatch_Handler,
		},
		{
			MethodName: "StopWatch",
			Handler:    _Tessellate_StopWatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tessellate.proto",
}

func init() { proto.RegisterFile("proto/tessellate.proto", fileDescriptor_tessellate_561282f3b06ec83b) }

var fileDescriptor_tessellate_561282f3b06ec83b = []byte{
	// 998 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0xef, 0x38, 0x69, 0x1a, 0xbf, 0x34, 0xbb, 0xde, 0x61, 0x55, 0x65, 0x23, 0x90, 0xc2, 0xec,
	0x42, 0x43, 0x96, 0xc6, 0x50, 0x84, 0xf8, 0xd3, 0x93, 0xdb, 0xb8, 0x95, 0x4b, 0xb0, 0xab, 0x49,
	0xda, 0xd2, 0xe5, 0x50, 0x4d, 0x92, 0xa1, 0x1b, 0xd5, 0x1b, 0x07, 0x7b, 0x52, 0xa8, 0xd0, 0x4a,
	0x68, 0xb9, 0xc0, 0x99, 0x23, 0xf0, 0x19, 0xb8, 0x73, 0xe2, 0x3b, 0xf0, 0x15, 0xb8, 0xc0, 0xa7,
	0x40, 0x1e, 0x3b, 0x5e, 0xb7, 0x1b, 0x9c, 0xac, 0xb4, 0xbd, 0xbd, 0x79, 0x7e, 0xef, 0xcd, 0xef,
	0xf7, 0xe6, 0xcd, 0x6f, 0x0c, 0x6b, 0x63, 0xdf, 0x13, 0x9e, 0x2e, 0x78, 0x10, 0x70, 0xd7, 0x65,
	0x82, 0x37, 0xa5, 0x03, 0xdf, 0x13, 0x81, 0xd7, 0x1f, 0x32, 0xb7, 0x99, 0xfa, 0x12, 0x70, 0xff,
	0x82, 0xfb, 0xd5, 0xd7, 0xcf, 0x3c, 0xef, 0xcc, 0xe5, 0x3a, 0x1b, 0x0f, 0x75, 0x36, 0x1a, 0x79,
	0x82, 0x89, 0xa1, 0x37, 0x0a, 0xa2, 0xc4, 0xea, 0xd6, 0xd9, 0x50, 0x3c, 0x9e, 0xf4, 0x9a, 0x7d,
	0xef, 0x89, 0xee, 0x5e, 0x7e, 0x25, 0x74, 0xe9, 0xee, 0x6f, 0x9c, 0xf1, 0xd1, 0xc6, 0x05, 0x73,
	0x87, 0x03, 0x26, 0xb8, 0xfe, 0x82, 0x11, 0x25, 0x93, 0xf7, 0xe0, 0xb5, 0x3d, 0x2e, 0x8e, 0x3d,
	0xff, 0x3c, 0x18, 0xb3, 0x3e, 0xa7, 0xfc, 0xeb, 0x09, 0x0f, 0x04, 0xbe, 0x07, 0x8a, 0x35, 0xa8,
	0xa0, 0x1a, 0xaa, 0xab, 0xdb, 0xea, 0x1f, 0xff, 0xfc, 0x99, 0xcb, 0xfb, 0x8a, 0x86, 0xa8, 0x62,
	0x0d, 0xc8, 0x10, 0xd4, 0x24, 0x1c, 0x63, 0xc8, 0xdb, 0xec, 0x09, 0x8f, 0x22, 0xa9, 0xb4, 0x43,
	0xdf, 0x11, 0xf3, 0x83, 0x8a, 0x52, 0x43, 0xf5, 0x55, 0x2a, 0x6d, 0x5c, 0x81, 0x95, 0x23, 0xee,
	0x07, 0x43, 0x6f, 0x54, 0xc9, 0xc9, 0xd0, 0xe9, 0x12, 0x57, 0xa1, 0x18, 0x9b, 0x41, 0x25, 0x5f,
	0xcb, 0xd5, 0x55, 0x9a, 0xac, 0xc9, 0x2e, 0xac, 0xb4, 0xd9, 0xa5, 0x37, 0x11, 0x01, 0xde, 0x82,
	0x15, 0x37, 0x32, 0x2b, 0xa8, 0x96, 0xab, 0x97, 0x36, 0xdf, 0x6c, 0xfe, 0x6f, 0xbf, 0x9a, 0x51,
	0x12, 0x9d, 0x66, 0x90, 0xdf, 0x10, 0x14, 0x22, 0x1f, 0xae, 0x41, 0x29, 0x41, 0x3f, 0x8c, 0x19,
	0xd2, 0xb4, 0x0b, 0xdf, 0x92, 0xd4, 0x15, 0xf9, 0x41, 0xb1, 0x06, 0x21, 0x9d, 0x03, 0x97, 0x45,
	0xb8, 0x57, 0xa9, 0xb4, 0x13, 0x8a, 0xf9, 0x14, 0xc5, 0x4f, 0xa0, 0xd0, 0x11, 0x4c, 0x4c, 0x82,
	0xca, 0x72, 0x0d, 0xd5, 0x6f, 0x65, 0x02, 0x8c, 0x02, 0x69, 0x9c, 0x40, 0x4c, 0xb8, 0xdb, 0x61,
	0x17, 0xfc, 0x25, 0x4e, 0x61, 0x56, 0x93, 0xc9, 0x47, 0x50, 0x4d, 0x9f, 0x65, 0xdc, 0xba, 0x05,
	0x8e, 0xf4, 0x0b, 0x50, 0xf7, 0xbd, 0x5e, 0x04, 0x26, 0xe6, 0x8f, 0x12, 0xfe, 0x5b, 0x50, 0x08,
	0x22, 0x5e, 0x8a, 0xe4, 0x75, 0x3f, 0x83, 0x57, 0x5c, 0x85, 0xd3, 0x38, 0x85, 0x54, 0x23, 0x98,
	0x09, 0x5c, 0x94, 0x82, 0xbb, 0x0e, 0xb0, 0xef, 0xf5, 0x16, 0x80, 0x97, 0x07, 0xc5, 0x39, 0x27,
	0xc7, 0x50, 0x8e, 0xcf, 0x35, 0xce, 0x78, 0x98, 0x3a, 0xca, 0x59, 0xa9, 0xe9, 0xaf, 0x71, 0x79,
	0x65, 0x56, 0xf9, 0x1f, 0x10, 0xdc, 0x09, 0xdb, 0x7f, 0x23, 0xd5, 0x17, 0x1d, 0x1f, 0xf2, 0x2d,
	0xac, 0x75, 0xb8, 0x88, 0x30, 0xc4, 0xe3, 0xf1, 0x8a, 0x91, 0xac, 0x25, 0x03, 0x1a, 0x5d, 0xc1,
	0xe9, 0xf4, 0x3d, 0x43, 0x80, 0x8d, 0xf1, 0xd8, 0xbd, 0xbc, 0xb1, 0x06, 0x48, 0xb2, 0xb9, 0xd4,
	0x5d, 0xd1, 0x20, 0x37, 0xf0, 0x2f, 0x25, 0xff, 0x22, 0x0d, 0x4d, 0xf2, 0x7b, 0x78, 0x08, 0x82,
	0xf9, 0xe2, 0x98, 0x89, 0xfe, 0xe3, 0x57, 0x8d, 0xa1, 0x0e, 0xb7, 0x3b, 0x93, 0x7e, 0x9f, 0x07,
	0xc1, 0x0e, 0x73, 0xdd, 0x1e, 0xeb, 0x9f, 0xc7, 0x3d, 0xb8, 0xee, 0x0e, 0x23, 0x77, 0xd9, 0xd0,
	0x9d, 0xf8, 0x3c, 0x89, 0xcc, 0x47, 0x91, 0xd7, 0xdc, 0xe4, 0x11, 0x68, 0x1d, 0xe1, 0x8d, 0x6f,
	0x02, 0x6f, 0x63, 0x04, 0x05, 0xd3, 0xf7, 0x3d, 0x3f, 0xc0, 0xb7, 0xa1, 0x64, 0x3b, 0xdd, 0x53,
	0xa3, 0xdd, 0x76, 0x8e, 0xcd, 0x96, 0xb6, 0x84, 0xcb, 0xa0, 0x86, 0x8e, 0x5d, 0xe7, 0xd0, 0x6e,
	0x69, 0x08, 0x03, 0x14, 0xda, 0xce, 0xce, 0x67, 0x66, 0x4b, 0x53, 0x30, 0x86, 0x5b, 0x96, 0xdd,
	0x35, 0xa9, 0x6d, 0xb4, 0x4f, 0x4d, 0x4a, 0x1d, 0xaa, 0xe5, 0xf0, 0x1d, 0x28, 0x5b, 0xf6, 0x91,
	0xd1, 0xb6, 0x5a, 0xa7, 0x47, 0x46, 0xfb, 0xd0, 0xd4, 0xf2, 0xa1, 0xeb, 0x73, 0xab, 0xd3, 0xb1,
	0xec, 0xbd, 0xd8, 0xb5, 0xdc, 0x20, 0xd3, 0xd1, 0xc0, 0xab, 0x50, 0xb4, 0x6c, 0x63, 0xa7, 0x6b,
	0x1d, 0x99, 0xda, 0x52, 0x58, 0x3d, 0xb6, 0x51, 0x83, 0x42, 0x71, 0x7a, 0xbd, 0x71, 0x09, 0x56,
	0x0e, 0x4c, 0xbb, 0x65, 0xd9, 0x7b, 0xda, 0x52, 0xb8, 0xa0, 0x87, 0xb6, 0x1d, 0x2e, 0x24, 0x9e,
	0x5d, 0xc3, 0x6a, 0x4b, 0x3c, 0x25, 0x58, 0x31, 0xb6, 0x1d, 0xda, 0x35, 0x5b, 0x5a, 0x0e, 0x17,
	0x21, 0xdf, 0x72, 0xec, 0x70, 0x7f, 0x15, 0x96, 0x23, 0x74, 0xcb, 0x8d, 0xfb, 0xa0, 0x3a, 0x63,
	0xee, 0xcb, 0xe7, 0x2c, 0xf4, 0x1b, 0x07, 0x07, 0xed, 0x93, 0xa8, 0x64, 0xcb, 0xec, 0x74, 0xa9,
	0x73, 0xa2, 0xa1, 0xcd, 0x7f, 0x8b, 0x00, 0xdd, 0x44, 0x6a, 0xf0, 0x25, 0x94, 0xaf, 0x88, 0x25,
	0xd6, 0xb3, 0x84, 0x76, 0x86, 0xac, 0x56, 0xdf, 0xc8, 0x48, 0x70, 0xce, 0x49, 0xe5, 0xd9, 0x5f,
	0x7f, 0xff, 0xac, 0x60, 0x52, 0xd6, 0x2f, 0xde, 0xd7, 0xbf, 0x99, 0x26, 0x7f, 0x8a, 0x1a, 0xf8,
	0x7b, 0x04, 0xab, 0x69, 0x85, 0xc5, 0xcd, 0x8c, 0x4a, 0x33, 0x9e, 0xd5, 0xea, 0x83, 0x8c, 0xf8,
	0x24, 0x98, 0x54, 0x25, 0x80, 0xbb, 0x18, 0x5f, 0x01, 0xa0, 0x7f, 0x67, 0x0d, 0x9e, 0xe2, 0x1f,
	0x11, 0xc0, 0x73, 0xb1, 0xc2, 0xef, 0xce, 0xe1, 0x7e, 0xe5, 0x4a, 0xcf, 0x23, 0xbe, 0x21, 0xf7,
	0x5d, 0x27, 0xe4, 0xda, 0xbe, 0xa9, 0xa1, 0x7d, 0xaa, 0x47, 0x6f, 0x6a, 0xd8, 0x8d, 0x9f, 0x10,
	0xa8, 0x7b, 0x53, 0xc9, 0xc2, 0xf5, 0xf9, 0xef, 0x71, 0x8c, 0x62, 0xfe, 0xcb, 0x4d, 0x74, 0x89,
	0xe4, 0x1d, 0xbc, 0x3e, 0x1f, 0x49, 0xd4, 0x96, 0x5f, 0x11, 0x94, 0x52, 0x1a, 0x86, 0x37, 0x32,
	0xf6, 0x78, 0x51, 0xeb, 0x32, 0xcf, 0x25, 0x79, 0x19, 0xc9, 0xc7, 0x12, 0xd5, 0x26, 0xd9, 0x58,
	0x10, 0x95, 0xce, 0xc2, 0x9d, 0xc2, 0x56, 0xfd, 0x82, 0xa0, 0xdc, 0xe2, 0x81, 0xf0, 0xbd, 0x1b,
	0x05, 0xf8, 0xa1, 0x04, 0xa8, 0x37, 0x5e, 0x0e, 0x20, 0xa6, 0x50, 0x34, 0x7a, 0x9e, 0x2f, 0xf6,
	0xbd, 0x1e, 0x7e, 0x2b, 0x7b, 0xa3, 0x05, 0x27, 0x69, 0x09, 0x7f, 0x09, 0xf0, 0x5c, 0xce, 0xb3,
	0xc7, 0xf4, 0xba, 0xea, 0xcf, 0x2f, 0x7e, 0x02, 0x6a, 0x22, 0xbd, 0xf8, 0x61, 0x66, 0xed, 0xab,
	0x02, 0x3d, 0xb7, 0xf4, 0xf6, 0xdb, 0x8f, 0x1e, 0xa4, 0x7e, 0xa7, 0xe3, 0xe0, 0xd4, 0xcf, 0xba,
	0x1e, 0x05, 0xf7, 0x0a, 0xf2, 0xf7, 0xf9, 0x83, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x82,
	0x66, 0x15, 0xce, 0x0b, 0x00, 0x00,
}
